name: Build and Push Docker Image

on:
  push:
    branches: [ main, development ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "branch_clean=${GITHUB_REF#refs/heads/}" | sed 's/[^a-zA-Z0-9]/-/g' >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.sha_short }} .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.branch_clean }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.branch_clean }}

      # Tag and push as latest only on main branch
      - name: Tag and push as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.sha_short }} ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:latest

      # Tag and push as development only on development branch
      - name: Tag and push as development
        if: github.ref == 'refs/heads/development'
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:${{ steps.vars.outputs.sha_short }} ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:development
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mmm-project:development 